"use client"

import { useEffect, useMemo, useRef, useState } from "react"
import { ArrowDownLeft, ArrowUpRight, Bell, CalendarDays, ChevronDown, CreditCard, Eye, EyeOff, LayoutDashboard, Menu, Pencil, Plus, Settings, Target, Trash2, TrendingUp, Wallet, X } from "lucide-react"

type Transaction = { id: number; name: string; category: string; date: string; value: number; type: "income" | "expense" }
type Goal = { id: number; name: string; current: number; target: number }
type Account = { id: number; name: string; type: string; value: number }

const initialTransactions: Transaction[] = []
const initialGoals: Goal[] = [{ id: 1, name: "Viagem para Europa eu e  fran", current: 0, target: 0 }, { id: 2, name: "Reserva de emergência", current: 0, target: 0 }]
const initialAccounts: Account[] = [{ id: 1, name: "Nubank principal", type: "Conta corrente", value: 0 }, { id: 2, name: "Cartão Platinum", type: "Fatura atual", value: 0 }]
const money = (n: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(n)
const categories = ["Salário", "Alimentação", "Moradia", "Transporte", "Lazer", "Renda extra", "Pensão", "Imprevistos", "Carro", "Gasolina", "Manutenção do carro", "Contas da casa", "Água", "Energia elétrica", "Internet", "Telefone", "Saúde", "Farmácia", "Educação", "Roupas", "Assinaturas", "Presentes", "Viagens", "Impostos", "Seguros", "Pets", "Dívidas", "Outros"]

export default function Page() {
  const [active, setActive] = useState("Visão geral")
  const [hidden, setHidden] = useState(false)
  const [modal, setModal] = useState(false)
  const [mobileNav, setMobileNav] = useState(false)
  const [period, setPeriod] = useState("Este mês")
  const [notifications, setNotifications] = useState(false)
  const [transactions, setTransactions] = useState<Transaction[]>(initialTransactions)
  const [goals, setGoals] = useState<Goal[]>(initialGoals)
  const [accounts, setAccounts] = useState<Account[]>(initialAccounts)
  const [hydrated, setHydrated] = useState(false)
  const [databaseReady, setDatabaseReady] = useState(false)
  const saveTimer = useRef<ReturnType<typeof setTimeout> | null>(null)
  const saveChain = useRef(Promise.resolve())
  const expenseCategories = categories.filter(c => c !== "Salário" && c !== "Renda extra")
  const [form, setForm] = useState({ name: "", value: "", category: expenseCategories[0], type: "expense" as "income" | "expense" })
  const [continueAdding, setContinueAdding] = useState(false)
  const [goalModal, setGoalModal] = useState(false)
  const [goalForm, setGoalForm] = useState({ name: "", target: "" })
  const [accountModal, setAccountModal] = useState(false)
  const [editingAccount, setEditingAccount] = useState<Account | null>(null)
  const [accountForm, setAccountForm] = useState({ name: "", type: "Conta corrente", value: "" })

  useEffect(() => {
    fetch("/api/finance").then(response => {
      if (!response.ok) throw new Error("Não foi possível carregar o banco")
      return response.json()
    }).then(data => {
      let nextData = data
      const saved = window.localStorage.getItem("nexa-finance-data-v2")
      if (!data.transactions.length && saved) {
        try {
          const localData = JSON.parse(saved)
          if (localData.transactions?.length || localData.goals?.length || localData.accounts?.length) nextData = localData
        } catch { window.localStorage.removeItem("nexa-finance-data-v2") }
      }
      setTransactions(nextData.transactions)
      setGoals(nextData.goals)
      setAccounts(nextData.accounts)
      setDatabaseReady(true)
    }).catch(error => console.error(error)).finally(() => setHydrated(true))
  }, [])
  useEffect(() => {
    if (!hydrated || !databaseReady) return
    if (saveTimer.current) clearTimeout(saveTimer.current)
    saveTimer.current = setTimeout(() => {
      const data = { transactions, goals, accounts }
      window.localStorage.setItem("nexa-finance-data-v2", JSON.stringify(data))
      saveChain.current = saveChain.current.catch(() => undefined).then(() => fetch("/api/finance", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data), keepalive: true })).then(response => { if (!response.ok) throw new Error("Não foi possível salvar no banco") }).catch(error => console.error(error))
    }, 250)
    return () => { if (saveTimer.current) clearTimeout(saveTimer.current) }
  }, [hydrated, databaseReady, transactions, goals, accounts])

  const income = useMemo(() => transactions.filter(t => t.type === "income").reduce((s, t) => s + t.value, 0), [transactions])
  const expenses = useMemo(() => transactions.filter(t => t.type === "expense").reduce((s, t) => s + t.value, 0), [transactions])
  const balance = income - expenses
  const mask = hidden ? "••••••" : undefined
  const display = (n: number) => mask ?? money(n)
  const addTransaction = () => { const value = Number(form.value.replace(",", ".")); if (!form.name.trim() || !value || value < 0) return; setTransactions([{ id: Date.now(), name: form.name.trim(), category: form.category, date: "Agora", value, type: form.type }, ...transactions]); setForm({ name: "", value: "", category: expenseCategories[0], type: "expense" }); if (!continueAdding) setModal(false) }
  const addGoal = () => { const target = Number(goalForm.target.replace(",", ".")); if (!goalForm.name.trim() || !target) return; setGoals([...goals, { id: Date.now(), name: goalForm.name, current: 0, target }]); setGoalForm({ name: "", target: "" }); setGoalModal(false) }
  const updateGoal = (id: number, patch: Partial<Goal>) => setGoals(goals.map(g => g.id === id ? { ...g, ...patch } : g))
  const deleteGoal = (id: number) => setGoals(goals.filter(g => g.id !== id))
  const openAccountEditor = (account?: Account) => { setEditingAccount(account ?? null); setAccountForm(account ? { name: account.name, type: account.type, value: String(account.value) } : { name: "", type: "Conta corrente", value: "" }); setAccountModal(true) }
  const saveAccount = () => { const value = Number(accountForm.value.replace(",", ".")); if (!accountForm.name.trim() || Number.isNaN(value) || value < 0) return; if (editingAccount) setAccounts(accounts.map(a => a.id === editingAccount.id ? { ...a, name: accountForm.name.trim(), type: accountForm.type, value } : a)); else setAccounts([...accounts, { id: Date.now(), name: accountForm.name.trim(), type: accountForm.type, value }]); setAccountModal(false) }
  const nav = [["Visão geral", LayoutDashboard], ["Transações", ArrowUpRight], ["Metas", Target], ["Contas e cartões", CreditCard]] as const

  return <main className="min-h-screen bg-background text-foreground">
    <aside className="fixed inset-y-0 left-0 hidden w-64 flex-col border-r border-border bg-sidebar px-5 py-6 lg:flex"><Brand /><Nav active={active} setActive={setActive} nav={nav} /><div className="mt-auto flex flex-col gap-5"><button onClick={() => setActive("Configurações")} className="flex items-center gap-3 px-3 py-3 text-sm text-muted-foreground"><Settings className="size-[18px]" />Configurações</button><Profile /></div></aside>
    <section className="lg:pl-64"><header className="flex items-center justify-between border-b border-border px-5 py-5 md:px-10"><div className="flex items-center gap-3"><button className="lg:hidden" onClick={() => setMobileNav(!mobileNav)} aria-label="Abrir menu"><Menu /></button><div><p className="text-sm text-muted-foreground">Domingo, 15 de junho de 2025</p><h1 className="mt-1 text-2xl font-semibold">Olá, Cleiton e Francieli</h1></div></div><div className="flex items-center gap-3"><button onClick={() => setNotifications(!notifications)} className="grid size-10 place-items-center rounded-xl border border-border text-muted-foreground" aria-label="Notificações"><Bell className="size-[18px]" /></button><button onClick={() => setModal(true)} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Plus className="size-4" />Nova transação</button></div></header>
      {mobileNav && <div className="flex flex-wrap gap-2 border-b border-border p-4 lg:hidden"><Nav active={active} setActive={(v) => { setActive(v); setMobileNav(false) }} nav={nav} /></div>}
      {notifications && <div className="mx-5 mt-4 rounded-xl border border-border bg-card p-4 text-sm md:mx-10"><b>Notificações</b><p className="mt-1 text-muted-foreground">Sua fatura vence em 5 dias. Você está dentro do orçamento mensal.</p></div>}
      {active === "Visão geral" ? <Dashboard {...{ hidden, setHidden, period, setPeriod, display, income, expenses, balance, transactions, setTransactions, goals, setGoalModal, updateGoal, deleteGoal, accounts }} /> : active === "Transações" ? <Transactions transactions={transactions} setTransactions={setTransactions} onAdd={() => setModal(true)} /> : active === "Metas" ? <Goals goals={goals} setGoalModal={setGoalModal} onUpdate={updateGoal} onDelete={deleteGoal} /> : active === "Contas e cartões" ? <Accounts accounts={accounts} onEdit={openAccountEditor} onAdd={() => openAccountEditor()} onDelete={(id: number) => setAccounts(accounts.filter(a => a.id !== id))} /> : <SettingsPanel />}
    </section>
    {modal && <TransactionModal form={form} setForm={setForm} continueAdding={continueAdding} setContinueAdding={setContinueAdding} onClose={() => setModal(false)} onSave={addTransaction} />}
    {goalModal && <GoalModal form={goalForm} setForm={setGoalForm} onClose={() => setGoalModal(false)} onSave={addGoal} />}
    {accountModal && <AccountModal form={accountForm} setForm={setAccountForm} editing={Boolean(editingAccount)} onClose={() => setAccountModal(false)} onSave={saveAccount} />}
  </main>
}

function Brand() { return <div className="flex items-center gap-3 px-2"><div className="grid size-9 place-items-center rounded-xl bg-primary text-primary-foreground"><Wallet className="size-5" /></div><b>Nexa Finance</b></div> }
function Profile() { return <div className="flex items-center gap-3 border-t border-border pt-5"><div className="grid size-9 place-items-center rounded-full bg-muted text-xs font-semibold">CF</div><div><p className="text-sm font-medium">Cleiton e Francieli</p><p className="text-xs text-muted-foreground">Plano Premium</p></div></div> }
function Nav({ active, setActive, nav }: { active: string; setActive: (v: string) => void; nav: readonly (readonly [string, any])[] }) { return <nav className="mt-10 flex flex-wrap gap-2 lg:flex-col">{nav.map(([label, Icon]) => <button key={label} onClick={() => setActive(label)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm ${active === label ? "bg-sidebar-accent text-sidebar-accent-foreground" : "text-muted-foreground hover:bg-sidebar-accent hover:text-foreground"}`}><Icon className="size-[18px]" />{label}</button>)}</nav> }

function Dashboard(p: any) {
  const { hidden, setHidden, period, setPeriod, display, income, expenses, balance, transactions, setTransactions, goals, setGoalModal, updateGoal, deleteGoal } = p; return <div className="space-y-6 px-5 py-7 md:px-10 md:py-9"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><h2 className="text-lg font-semibold">Visão geral</h2><p className="mt-1 text-sm text-muted-foreground">Acompanhe sua saúde financeira em um só lugar.</p></div><label className="flex w-fit items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm text-muted-foreground"><CalendarDays className="size-4" /><select value={period} onChange={e => setPeriod(e.target.value)} className="bg-transparent outline-none"><option>Este mês</option><option>Últimos 3 meses</option><option>Este ano</option></select><ChevronDown className="size-4" /></label></div><div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-primary p-5 text-primary-foreground"><div className="flex justify-between text-sm opacity-80">Saldo disponível<button onClick={() => setHidden(!hidden)} aria-label="Alternar visibilidade">{hidden ? <EyeOff className="size-4" /> : <Eye className="size-4" />}</button></div><p className="mt-5 text-3xl font-semibold">{display(balance)}</p><p className="mt-5 text-xs opacity-80"><TrendingUp className="mr-1 inline size-3" />12,8% vs. mês anterior</p></div><Stat title="Receitas" value={income} icon={ArrowDownLeft} color="text-chart-2" /><Stat title="Despesas" value={expenses} icon={ArrowUpRight} color="text-chart-4" /></div><div className="grid gap-6 xl:grid-cols-[1.45fr_1fr]"><Chart /><Categories expenses={expenses} /></div><div className="grid gap-6 xl:grid-cols-[1.45fr_1fr]"><Transactions transactions={transactions.slice(0, 5)} setTransactions={setTransactions} /><Goals goals={goals} setGoalModal={setGoalModal} onUpdate={updateGoal} onDelete={deleteGoal} /></div></div>
}
function Stat({ title, value, icon: Icon, color }: any) { return <div className="rounded-2xl border border-border bg-card p-5"><div className="flex justify-between text-sm text-muted-foreground">{title}<Icon className={`size-5 ${color}`} /></div><p className="mt-5 text-2xl font-semibold">{money(value)}</p><p className={`mt-2 text-xs ${color}`}>+8,4% <span className="text-muted-foreground">este mês</span></p></div> }
function Chart() { return <div className="rounded-2xl border border-border bg-card p-5 md:p-6"><h3 className="font-semibold">Fluxo de caixa</h3><p className="mt-1 text-sm text-muted-foreground">Receitas e despesas ao longo do tempo</p><div className="mt-8 flex h-48 items-end gap-2 md:gap-4">{[42, 58, 49, 68, 54, 77, 62, 84, 57, 70, 65, 90].map((h, i) => <div key={i} className="flex flex-1 items-end gap-1.5"><i className="w-1/2 rounded-t-sm bg-primary/80" style={{ height: `${h}%` }} /><i className="w-1/2 rounded-t-sm bg-chart-4/70" style={{ height: `${Math.max(18, h - 25)}%` }} /></div>)}</div><div className="mt-4 flex justify-between text-[11px] text-muted-foreground"><span>Jul</span><span>Set</span><span>Nov</span><span>Jan</span><span>Mar</span><span>Mai</span><span>Jun</span></div><div className="mt-5 flex gap-5 text-xs text-muted-foreground"><span className="text-primary">● Receitas</span><span className="text-chart-4">● Despesas</span></div></div> }
function Categories({ expenses }: { expenses: number }) { return <div className="rounded-2xl border border-border bg-card p-5 md:p-6"><h3 className="font-semibold">Gastos por categoria</h3><p className="mt-1 text-sm text-muted-foreground">Distribuição deste mês</p><div className="mt-7 flex items-center gap-6"><div className="grid size-36 shrink-0 place-items-center rounded-full" style={{ background: "conic-gradient(hsl(var(--primary)) 0 59%, hsl(var(--chart-2)) 59% 83%, hsl(var(--chart-3)) 83% 93%, hsl(var(--chart-4)) 93% 100%)" }}><div className="grid size-24 place-items-center rounded-full bg-card"><b>{money(expenses)}</b><small className="text-[10px] text-muted-foreground">total gasto</small></div></div><div className="flex flex-col gap-3 text-xs">{[["Moradia", 2400, "bg-primary"], ["Alimentação", 980, "bg-chart-2"], ["Transporte", 420, "bg-chart-3"], ["Lazer", 260, "bg-chart-4"]].map(([n, v, c]) => <div className="flex items-center gap-2" key={n as string}><i className={`size-2 rounded-full ${c}`} /><span className="text-muted-foreground">{n}</span><b className="ml-auto">{money(v as number)}</b></div>)}</div></div></div> }
function Transactions({ transactions, setTransactions, onAdd }: { transactions: Transaction[]; setTransactions: (v: Transaction[]) => void; onAdd?: () => void }) { return <div className="rounded-2xl border border-border bg-card p-5 md:p-6"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Transações</h3><p className="mt-1 text-sm text-muted-foreground">Seus lançamentos recentes</p></div>{onAdd && <button onClick={onAdd} className="flex items-center gap-1 text-sm text-primary"><Plus className="size-4" />Adicionar</button>}</div><div className="mt-5 flex flex-col divide-y divide-border">{transactions.length ? transactions.map(t => <div key={t.id} className="flex items-center gap-3 py-3.5"><div className={`grid size-10 place-items-center rounded-xl ${t.type === "income" ? "bg-chart-2/15 text-chart-2" : "bg-muted text-muted-foreground"}`}>{t.type === "income" ? <ArrowDownLeft className="size-[18px]" /> : <Wallet className="size-[18px]" />}</div><div className="flex-1"><p className="text-sm font-medium">{t.name}</p><p className="text-xs text-muted-foreground">{t.category} · {t.date}</p></div><b className={t.type === "income" ? "text-chart-2" : ""}>{t.type === "income" ? "+" : "−"}{money(t.value)}</b><button onClick={() => setTransactions(transactions.filter(x => x.id !== t.id))} aria-label={`Excluir ${t.name}`} className="text-muted-foreground hover:text-destructive"><Trash2 className="size-4" /></button></div>) : <p className="py-8 text-center text-sm text-muted-foreground">Nenhuma transação encontrada.</p>}</div></div> }
function Goals({ goals, setGoalModal, onUpdate, onDelete }: { goals: Goal[]; setGoalModal: (v: boolean) => void; onUpdate: (id: number, patch: Partial<Goal>) => void; onDelete: (id: number) => void }) { return <div className="rounded-2xl border border-border bg-card p-5 md:p-6"><div className="flex justify-between"><div><h3 className="font-semibold">Metas de economia</h3><p className="mt-1 text-sm text-muted-foreground">Acompanhe e atualize seus objetivos</p></div><Target className="size-5 text-primary" /></div><div className="mt-6 flex flex-col gap-5">{goals.map(g => <div key={g.id}><div className="flex items-center justify-between gap-3 text-sm"><span className="font-medium">{g.name}</span><div className="flex items-center gap-2"><b>{g.target > 0 ? Math.round(g.current / g.target * 100) : 0}%</b><button onClick={() => onDelete(g.id)} aria-label={`Excluir meta ${g.name}`} className="text-muted-foreground hover:text-destructive"><Trash2 className="size-4" /></button></div></div><div className="mt-2 h-2 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${g.target > 0 ? Math.min(100, g.current / g.target * 100) : 0}%` }} /></div><div className="mt-2 flex items-center justify-between gap-3 text-xs text-muted-foreground"><span>{money(g.current)} de {money(g.target)}</span><input aria-label={`Valor guardado em ${g.name}`} value={g.current} onChange={e => onUpdate(g.id, { current: Math.max(0, Number(e.target.value)) })} type="number" min="0" className="w-28 rounded-lg border border-border bg-background px-2 py-1 text-right text-foreground" /></div></div>)}</div><button onClick={() => setGoalModal(true)} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl border border-border py-2.5 text-sm"><Plus className="size-4" />Criar nova meta</button></div> }
function Accounts({ accounts, onEdit, onAdd, onDelete }: { accounts: Account[]; onEdit: (account: Account) => void; onAdd: () => void; onDelete: (id: number) => void }) { return <div className="space-y-6 px-5 py-7 md:px-10"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-semibold">Contas e cartões</h2><p className="mt-1 text-sm text-muted-foreground">Edite seus saldos e cartões a qualquer momento.</p></div><button onClick={onAdd} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Plus className="size-4" />Adicionar</button></div><div className="grid gap-4 md:grid-cols-2">{accounts.map(a => <div key={a.id} className="rounded-2xl border border-border bg-card p-6"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-primary/15 text-primary">{a.type.includes("Cartão") ? <CreditCard /> : <Wallet />}</div><div><p className="font-medium">{a.name}</p><p className="text-sm text-muted-foreground">{a.type}</p></div><button onClick={() => onEdit(a)} aria-label={`Editar ${a.name}`} className="ml-auto rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-foreground"><Pencil className="size-4" /></button><button onClick={() => onDelete(a.id)} aria-label={`Excluir ${a.name}`} className="rounded-lg p-2 text-muted-foreground hover:bg-muted hover:text-destructive"><Trash2 className="size-4" /></button></div><p className="mt-7 text-2xl font-semibold">{money(a.value)}</p></div>)}</div></div> }
function AccountModal({ form, setForm, editing, onClose, onSave }: any) { return <Modal title={editing ? "Editar conta ou cartão" : "Adicionar conta ou cartão"} subtitle="Atualize os dados para acompanhar seu saldo." onClose={onClose}><div className="flex flex-col gap-4"><input autoFocus value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="rounded-xl border border-border bg-background px-3 py-3" placeholder="Nome da conta ou cartão" /><select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })} className="rounded-xl border border-border bg-background px-3 py-3"><option>Conta corrente</option><option>Conta poupança</option><option>Cartão de crédito</option><option>Fatura atual</option></select><input value={form.value} onChange={e => setForm({ ...form, value: e.target.value })} type="number" min="0" step="0.01" className="rounded-xl border border-border bg-background px-3 py-3" placeholder="Saldo ou valor da fatura" /><button onClick={onSave} className="rounded-xl bg-primary py-3 font-semibold text-primary-foreground">{editing ? "Salvar alterações" : "Adicionar"}</button></div></Modal> }
function SettingsPanel() { return <div className="space-y-6 px-5 py-7 md:px-10"><h2 className="text-2xl font-semibold">Configurações</h2><div className="max-w-xl rounded-2xl border border-border bg-card p-6"><p className="font-medium">Perfil financeiro</p><p className="mt-2 text-sm text-muted-foreground">Seus dados ficam salvos neste dispositivo. A conexão com banco de dados poderá ser adicionada depois.</p><button className="mt-5 rounded-xl border border-border px-4 py-2 text-sm">Salvar preferências</button></div></div> }
function TransactionModal({ form, setForm, continueAdding, setContinueAdding, onClose, onSave }: any) { return <Modal title="Nova transação" subtitle="Registre um novo lançamento." onClose={onClose}><div className="flex flex-col gap-4"><div className="flex gap-2"><button onClick={() => setForm({ ...form, type: "expense" })} className={`flex-1 rounded-xl border py-2 text-sm ${form.type === "expense" ? "border-primary bg-primary/10 text-primary" : "border-border"}`}>Despesa</button><button onClick={() => setForm({ ...form, type: "income", category: "Salário" })} className={`flex-1 rounded-xl border py-2 text-sm ${form.type === "income" ? "border-chart-2 bg-chart-2/10 text-chart-2" : "border-border"}`}>Receita</button></div><input autoFocus value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="rounded-xl border border-border bg-background px-3 py-3" placeholder="Descrição" /><input value={form.value} onChange={e => setForm({ ...form, value: e.target.value })} type="number" min="0" className="rounded-xl border border-border bg-background px-3 py-3" placeholder="Valor (R$)" /><select aria-label="Categoria da transação" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} className="rounded-xl border border-border bg-background px-3 py-3">{(form.type === "income" ? ["Salário", "Renda extra"] : categories.filter(c => c !== "Salário" && c !== "Renda extra")).map(c => <option key={c}>{c}</option>)}</select><label className="flex cursor-pointer items-center gap-3 text-sm text-muted-foreground"><input type="checkbox" checked={continueAdding} onChange={e => setContinueAdding(e.target.checked)} className="size-4 accent-primary" />Continuar adicionando lançamentos</label><button onClick={onSave} className="rounded-xl bg-primary py-3 font-semibold text-primary-foreground">Adicionar transação</button></div></Modal> }
function GoalModal({ form, setForm, onClose, onSave }: any) { return <Modal title="Nova meta" subtitle="Defina um objetivo para acompanhar." onClose={onClose}><div className="flex flex-col gap-4"><input autoFocus value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className="rounded-xl border border-border bg-background px-3 py-3" placeholder="Nome da meta" /><input value={form.target} onChange={e => setForm({ ...form, target: e.target.value })} type="number" min="1" className="rounded-xl border border-border bg-background px-3 py-3" placeholder="Valor alvo (R$)" /><button onClick={onSave} className="rounded-xl bg-primary py-3 font-semibold text-primary-foreground">Criar meta</button></div></Modal> }
function Modal({ title, subtitle, onClose, children }: any) { return <div className="fixed inset-0 z-50 grid place-items-center bg-background/80 p-5 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="w-full max-w-md rounded-2xl border border-border bg-card p-6"><div className="flex justify-between"><div><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{subtitle}</p></div><button onClick={onClose} aria-label="Fechar"><X className="size-5" /></button></div><div className="mt-6">{children}</div></div></div> }
