"use client"

import { useState } from "react"
import { Plus, Trash2, ToggleLeft, ToggleRight, Download } from "lucide-react"

type Transaction = { category: string; value: number; type: string }
type Budget = { id: number; category: string; limit: number }
type Recurring = { id: number; name: string; category: string; value: number; type: "income" | "expense"; frequency: string; active: boolean }
const money = (n: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(n)
const categories = ["Alimentação", "Moradia", "Transporte", "Lazer", "Saúde", "Assinaturas", "Outros"]

export function Budgets({ budgets, transactions, onChange }: { budgets: Budget[]; transactions: Transaction[]; onChange: (v: Budget[]) => void }) {
  const [category, setCategory] = useState(categories[0]); const [limit, setLimit] = useState("")
  const add = () => { const value = Number(limit.replace(",", ".")); if (!value) return; onChange([...budgets, { id: Date.now(), category, limit: value }]); setLimit("") }
  return <section className="space-y-6 px-5 py-7 md:px-10"><div><h2 className="text-2xl font-semibold">Orçamentos</h2><p className="mt-1 text-sm text-muted-foreground">Defina limites e acompanhe seus gastos por categoria.</p></div><div className="flex flex-col gap-2 rounded-2xl border border-border bg-card p-4 md:flex-row"><select value={category} onChange={e => setCategory(e.target.value)} className="rounded-xl border border-border bg-background px-3 py-3">{categories.map(c => <option key={c}>{c}</option>)}</select><input value={limit} onChange={e => setLimit(e.target.value)} type="number" min="1" placeholder="Limite mensal (R$)" className="rounded-xl border border-border bg-background px-3 py-3" /><button onClick={add} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground"><Plus className="size-4" />Criar orçamento</button></div><div className="grid gap-4 md:grid-cols-2">{budgets.length ? budgets.map(b => { const spent = transactions.filter(t => t.type === "expense" && t.category === b.category).reduce((s, t) => s + t.value, 0); const percent = Math.min(100, spent / b.limit * 100); return <article key={b.id} className="rounded-2xl border border-border bg-card p-5"><div className="flex justify-between"><div><h3 className="font-semibold">{b.category}</h3><p className="text-sm text-muted-foreground">{money(spent)} de {money(b.limit)}</p></div><button aria-label={`Excluir orçamento ${b.category}`} onClick={() => onChange(budgets.filter(x => x.id !== b.id))} className="text-muted-foreground hover:text-destructive"><Trash2 className="size-4" /></button></div><div className="mt-5 h-3 rounded-full bg-muted"><div className={`h-full rounded-full ${percent >= 100 ? "bg-destructive" : percent >= 80 ? "bg-chart-4" : "bg-primary"}`} style={{ width: `${percent}%` }} /></div><p className="mt-2 text-xs text-muted-foreground">{Math.round(percent)}% utilizado</p></article> }) : <div className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Crie seu primeiro orçamento para acompanhar os limites.</div>}</div></section>
}

export function RecurringList({ items, onChange }: { items: Recurring[]; onChange: (v: Recurring[]) => void }) { const [name, setName] = useState(""); const [value, setValue] = useState(""); const add = () => { const amount = Number(value.replace(",", ".")); if (!name.trim() || !amount) return; onChange([...items, { id: Date.now(), name: name.trim(), category: "Assinaturas", value: amount, type: "expense", frequency: "Mensal", active: true }]); setName(""); setValue("") }; return <section className="space-y-6 px-5 py-7 md:px-10"><div><h2 className="text-2xl font-semibold">Recorrências</h2><p className="mt-1 text-sm text-muted-foreground">Organize despesas fixas como aluguel, assinaturas e contas.</p></div><div className="flex flex-col gap-2 rounded-2xl border border-border bg-card p-4 md:flex-row"><input value={name} onChange={e => setName(e.target.value)} placeholder="Nome da recorrência" className="rounded-xl border border-border bg-background px-3 py-3" /><input value={value} onChange={e => setValue(e.target.value)} type="number" min="1" placeholder="Valor mensal (R$)" className="rounded-xl border border-border bg-background px-3 py-3" /><button onClick={add} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 font-semibold text-primary-foreground"><Plus className="size-4" />Adicionar</button></div><div className="flex flex-col gap-3">{items.length ? items.map(item => <article key={item.id} className="flex items-center gap-4 rounded-2xl border border-border bg-card p-4"><div className="min-w-0 flex-1"><p className="font-medium">{item.name}</p><p className="text-sm text-muted-foreground">{money(item.value)} · {item.frequency}</p></div><button onClick={() => onChange(items.map(x => x.id === item.id ? { ...x, active: !x.active } : x))} className={item.active ? "text-primary" : "text-muted-foreground"} aria-label="Alternar recorrência">{item.active ? <ToggleRight /> : <ToggleLeft />}</button><button onClick={() => onChange(items.filter(x => x.id !== item.id))} aria-label={`Excluir ${item.name}`} className="text-muted-foreground hover:text-destructive"><Trash2 className="size-4" /></button></article>) : <div className="rounded-2xl border border-dashed border-border p-8 text-center text-sm text-muted-foreground">Nenhuma recorrência cadastrada.</div>}</div></section> }

export function ExportButton({ transactions }: { transactions: Transaction[] }) { const download = () => { const csv = ["Descrição,Categoria,Tipo,Valor", ...transactions.map(t => `${t.category},${t.category},${t.type},${t.value}`)].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = "relatorio-financeiro.csv"; link.click(); URL.revokeObjectURL(url) }; return <button onClick={download} className="flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-sm"><Download className="size-4" />Exportar CSV</button> }

export const FinancePanels = { Budgets, RecurringList, ExportButton }
